config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"

  #Defines list paths
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :chats do
    resources :messages, only: [:create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }

  has_one_attached :photo
end

app/models/chat.rb
class Chat < ApplicationRecord
  acts_as_chat

  has_many :messages, dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true

  has_one_attached :photo
end

app/models/message.rb
class Message < ApplicationRecord
  acts_as_message

  belongs_to :chat
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/models/tool_call.rb
class ToolCall < ApplicationRecord
  acts_as_tool_call
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.summary = movie_summary(@bookmark)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_content
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id, :summary)
  end

  def movie_summary(bookmark)
    prompt = <<-PROMPT
      Please give me a short summary about the movie #{bookmark.movie.title}
      Please keep it around 50 words.
    PROMPT
    RubyLLM.chat.ask(prompt).content
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = Chats.all
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new', status: :unprocessable_content
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  prompt = <<-PROMPT
    You are a chatbox to help users find movies they would like
    I am a user who likes movie
    Give me a list of a few movies that I would what I am interested in
    Give them in a list with a short summary attached.
    PROMPT

  def create
    @chat = Chat.find_by(id: params[:chat_id])

    if @chat.nil?
      @chat = Chat.create
    end

    @message = @chat.messages.new(message_params)
    @message.role = "user"

    if @message.save
      @chat = RubyLLM.chat(messages: @chat.messages.map(&:as_json))
      @response = chat.with_instructions(prompt).ask(@message.content)
      @ai_message = @chat.messages.new(content: @response.content, user: "ai")
      @ai_message.save

      respond_to do |format|
        format.json { render json: { chat_id: @chat.id, user_message: @message.content, ai_message: @ai_message.content } }
      end

  private

  def message_params
    params.require(:messages),permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/bookmarks/new.html.erb
<h1>Okay the bookmark new worked, will need to make a form</h1>

<%= simple_form_for [@list ,@bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">

  <div class="banner" style="background-image: url('<%= asset_path("popcorn.avif") %>');">
    <div class="container">
      <h1>Movie lists for your friends and more!</h1>
      <p>Add movies and comment your thoughts.</p>
    </div>
  </div>

  <ul class="card-grid">
    <% @lists.each do |l| %>
      <li>
        <div class="card">
          <% if l.photo.attached? %>
            <%= cl_image_tag l.photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
          <div class="card-info">
            <%= link_to "#{l.name}", list_path(l[:id]), class: "list-link" %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

  <%= link_to 'Create a new list <3', new_list_path, class: "new-list-button" %>
  <button type="button" id="chat-open-button">Open Chat</button>
  <%= render "shared/chatbox" %>
</div>

app/views/lists/new.html.erb
<h1>Okay this one worked, will need a form later<h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
<h1 style="text-align:center; padding: 8px 0px;"><%= @list.name %></h1>

<div class="movie-list">
    <% @list.bookmarks.each do |b| %>
      <div class="list-card">
        <h3><strong><%= b.movie.title %></strong></h3>
        <p><strong>Summary: </strong><%= b.summary %></p>
        <p><strong>Comments: </strong> <%= b.comment %></p>
        <%= link_to "Delete me!", bookmark_path(b), class: "delete-button", data: { turbo_method: :delete, turbo_confirm: "Are you sure sweetie" } %>
      </div>
    <% end %>

    <%= link_to "Add new bookmark", new_list_bookmark_path(@list), style: "text-align: center;" %>
    <%= link_to "Go Home hunny", lists_path, style: "text-align: center;" %>
</div>

app/views/shared/_chatbox.html.erb
<div id="modal-overlay" class="modal-overlay">
  <div class="modal-content">
    <h2>This is the Modal Content</h2>
    <%# <%= simple_form_for[@chat, @message], url: chat_messages_path, data: { } %> %>
    <button type="button" id="chat-close-button">Close Chat</button>
  </div>
</div>